mlcommons/ck

ck/kernel.py

Hi,
This PR adds a new function to the kernel: run_and_get_stdout. The function runs a command and returns its standard output as a string. I needed this feature to make ck-env's detect in platform.cpu work with OS X (the PR for that follows shortly) and thought it would be nice to have it as a part of general API.

Add run_and_get_stdout function

---

ck/kernel.py

Minor PR to fix a minor issue with `run_and_get_stdout()`. Without it calling `run_and_get_stdout()` with generate the following error:
ValueError: I/O operation on closed file

Fix issue when run_and_get_stdout() calls Popen.communicate() twice

---

.gitignore
.travis.yml
README.md
ck/test_kernel.py

Hi,
This PR adds integration with travis-ci.org. You can check the Travis build for the fork to see how it looks: https://travis-ci.org/dsavenko/ck . 
I added one very simple test ('test_safe_float'), because without any tests Travis build is next to useless. This test and the 'tests/' folder should be refactored in subsequent PRs about testing. 
After merging, you need to log in travis-ci.org and enable travis for the CK repository.
P.S. The button is README doesn't look as intended yet, because I changed the URL to the future URL of the upstream travis build, which doesn't yet exist. It should start working as soon as you enable Travis for the project.

Integrate with Travis

---

README.md
appveyor.yml

Hi,
This PR enables continuous integration on Windows. 
Travis-CI does not support Windows, so this PR makes use of [AppVeyor](https://www.appveyor.com/), which is similar to Travis, but for Windows.
After merging you need to log in [AppVeyor](https://www.appveyor.com/) with the `ctuning` account and add CK project. May be, you'll need to initiate a single build for everything to work.

Continuous integration for Windows

---

.gitignore
.travis.yml
README.md

Hi,
This PR enables code coverage measurement by tests. It uses the [Coveralls](http://coveralls.io/) service, which is free for open source projects. 
After merging, you need to log in [Coveralls](http://coveralls.io/) with the cTuning github account. It asks you to select payment plan — **you can skip this step**. Just move mouse to the left (where the menu is) and choose 'Add repo'. 
A list of your github repos appear. Select 'on' for CK. That's it!
You may need to build the repo again in travis. After that you can navigate to https://coveralls.io/github/ctuning/ck and check the coverage as well as detailed reports on which lines are covered.
The PR also adds the 'coverage' badge to README (next to the 'build' badge).
**Warning! This PR depends on the 'tests' …

Measure code coverage by tests

---

ck/repo/module/kernel/test/test_kernel.py
ck/repo/module/kernel/test/test_mgmt.py
ck/repo/module/test/module.py

Hi,
This PR improves tests failure reporting. With it, `ck run test` return code depends on the number of failed tests. Previously, it returned 0 even if there were failed tests, which made it hard to use in shell scripts. Now, it returns 0, if all tests passed. If some tests failed, it returns `100 + number of failed tests`. Return codes in between 1 and 100 are reserved for test execution errors. 
So, with this PR, the caller can easily detect if some tests failed, distinguish this case from the case when test execution failed, and even detect, how many tests failed, just by the return code, without parsing the command output.
Also, this PR fixes some tests, which were failing under Windows (#63).

Improve tests failure reporting, fix Windows tests

---

ck/kernel.py
ck/repo/module/test/test_util.py

Hi,
This small PR makes sure `ck.type_long` (which was in the kernel before) is used for operations with long numbers in the kernel. Also, it introduces `ck.string_io`, which is just an alias for Python's `StringIO`. 
It's needed to facilitate bilingual coding (when the same code works on Python 2 and Python 3), since `StringIO` is imported differently in P2 and P3, and P3 lacks `long`.

Bilingual long and StringIO

---

ck/kernel.py

This pull request deals with the situation when an action is missing from the module's .cm/meta.json declaration dictionary.
The old behaviour was to immediately return with an error, stating that the method is unavailable.
The new proposed behaviour is to also check if the module has a 'default_action_name' defined. If it is defined and the corresponding function exists, this default function will be called instead.
If the 'default_action_name' is not defined, the behaviour is exactly the same as it used to be (an error is generated).
The new behaviour opens a new dimension for extending CK by allowing a CK module to intercept calls to another module, augmenting or substituting the functionality.

added 'default_action_name' key to module's .cm/meta.json to allow intercepting any undefined method

---

ck/repo/module/repo/module.py

The ZIP file was downloaded and extracted but the contents of .ckr.json where never read. This meant the the UID was blank and so was auto-generated.

Fixed issue #91 where adding a remote repo generated a new UID

---

docs/list_of_scripts.md
docs/mlperf-automation/README.md
docs/mlperf-education-workgroup.md
docs/tutorials/sc22-scc-mlperf.md
docs/tutorials/sc22-scc-mlperf2.md

Added SCC'22 tutorial to run the MLPerf object detection benchmark via CM with RetinaNet, Open Images and ONNX runtime.

SCC'22 tutorial to run the MLPerf inference benchmark

---

cm-mlops/script/get-generic-python-lib/_cm.json
cm-mlops/script/get-ml-model-resnet50-tvm/README.md
cm-mlops/script/get-ml-model-resnet50-tvm/_cm.json
cm-mlops/script/get-ml-model-resnet50-tvm/customize.py
cm-mlops/script/get-ml-model-resnet50-tvm/process.py

Added variation `tune-model` for `get-ml-model-resnet50-tvm` to tune ResNet50 using MetaSchedule. Also it is possible to compile model using already existing tuning records

Introducing model tuning using TVM MetaSchedule

---

cm-mlops/script/get-tvm-model/process.py

Small hotfix for import meta_schedule in `get-tvm-model`

Fix import

---

cm-mlops/script/app-mlperf-inference/_cm.yaml
cm-mlops/script/get-tvm-model/process.py

Changed `batch_size` and decrease maximum number of trials for tuning for `tvm` backend

Change batchsize for tvm backend

---

cm-mlops/script/detect-os/customize.py

This needs to be set at the command level, because it is sometimes called with sudo which drops the environment.
This breaks a bit the format of this file, but I don't see a cleaner way to pass this.

Non-interactive apt-get

---

cm-mlops/script/reproduce-mlperf-inference-nvidia/README-about.md

To use the tar-balls downloaded above, you have to specify --tar_file not --input.

reproduce-mlperf-inference-nvidia: Update README-about.md

---

cm-mlops/cfg/benchmark-hardware-compute/google-tpu.json
cm-mlops/cfg/benchmark-hardware-compute/habana-gaudi.json
cm-mlops/cfg/benchmark-list/mlperf-inference.yaml
cm-mlops/script/gui/playground_howtorun.py
cm-mlops/script/gui/script.py
cm-mlops/script/run-mlperf-inference-app/customize.py
cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/core.py
cm/cmind/repo.py
cm/cmind/repo/automation/repo/_cm.json
cm/cmind/repo/automation/repo/module.py
cm/cmind/repos.py
cmr.yaml
docs/taskforce.md

- added support to handle broken CM repositories: https://github.com/mlcommons/ck/issues/1177
- added "cm checkout repo mlcommons@ck --branch=dev" to make it easier to switch branches
- added "cm import repo" to import repository in the current directory

v2.0.3 release

---

cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/repos.py

We got requests to install extra PIP packages when pulling CM repositories. This flag will force to install extra dependencies from requirements.txt file when pulling such CM repositories ...

Added install_python_requirements to the CM repo description

---

cm/CHANGES.md
cm/cmind/__init__.py

Hi @arjunsuresh and @anandhu-eng,
This release has a nice feature to install `requirements.txt` from pulled CM repositories if `_cm.yaml` has `install_python_requirements: true`
It should be backwards compatible and was based on several requests I received in the past few months.
Feel free to use it if needed ...
Thank you and have a good weekend!

v2.4.0: added support to install requirements.txt from pulled CM repositories

---

cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/repo/automation/core/module.py
cm/docs/cmx/install.md
cm/setup_install.bat

Ref: https://github.com/mlcommons/ck/issues/1305

fixed cmx init

---

cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/core.py
cm/cmind/repo/automation/repo/module.py
cm/cmind/repos.py
cm/debugx.py

Several improvements to CM/CMX core based on user feedback:
* https://github.com/mlcommons/ck/issues/1308
* https://github.com/mlcommons/ck/issues/1309

V3.0.3: several improvements

---

cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/utils.py

https://github.com/mlcommons/ck/issues/1313

v3.1.0: simplified and changed process_input function API

---

cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/config.py
cm/cmind/core.py
cm/cmind/repo.py
cm/cmind/repos.py
cm/cmind/utils.py
cm/docs/cmx/README.md

I added many important features to CMX pending for a very long:
- added `utils.test_input` to test if input has keys and report them as error
- added `prefix_cmx` key to cmr.yaml to customize `cmx pull repo`
- improved CMX logging (-log and -logfile):  https://github.com/mlcommons/ck/issues/1317
- print control flags in help (cmx -h | cmx -help):   https://github.com/mlcommons/ck/issues/1318
- fail if control flag is not recognized:  https://github.com/mlcommons/ck/issues/1315
- added -repro flag to record various info to cmx-repro directory:  https://github.com/mlcommons/ck/issues/1319
- print call stack when error > 32 to be able to trace error cause:  https://github.com/mlcommons/ck/issues/1320
can be combined with -log=debug and -logfile

V3.2.0: many important improvements

---

README.md
cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/core.py

- fixed action `help` and flag `-h` to work with all automations:
https://github.com/mlcommons/ck/issues/1325

fixed action `help` and flag `-h` to work with all automations

---

cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/core.py

CMX/CM: V3.2.5 release
- CMX: improved logging
- CMX: improved error handling (show module path and line number)
- CMX: fixed bug when detecting unknown control flag
- CMX: do not change output to json if -j or --json
just print json in the end ...

V3.2.5 release

---

cm/CHANGES.md
cm/README.md
cm/cmind/__init__.py
cm/cmind/core.py
cm/cmind/utils.py

- Fix type of "unknown_keys" to list to be serializable:   https://github.com/mlcommons/ck/issues/1335
- Added support to print warning instead of error:  (useful for help)

v2.3.6: regular improvements and bug fixes

---

cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/cli.py
cm/cmind/core.py
cm/setup.py
tests/script/test_docker.py

- fixed minor bug with JSON console output
- fixed minor bug with console in cmind.x function

CM/CMX v3.2.9: fixing minor bugs

---

README.md
cm/CHANGES.md
cm/cmind/__init__.py
cm/cmind/utils.py

Added reusable functions  from MLPerf automations:
- added utils.flatten_dict
- added utils.safe_int
- added utils.safe_float
- added utils.get_set
- added utils.digits

CM/CMX V3.4.2: new reusable functions
